--- # Build an Apache Web Server
- hosts: apacheweb
  user: test
  sudo: yes
  connection: ssh
  gather_facts: yes
  vars:
    apache_pkg: httpd
    distribution: "{{ ansible_os_family }}" 
    apache_version: 2.4
    apache_dir: /var/www/sample
    apache_fqdn: tcox4.mylabserver.com
  tasks:
    - name: Install the Web Server Package
      yum: pkg={{ apache_pkg }} state=latest
    - name: Create the web server directory
      file: path={{ apache_dir }} state=directory mode=644
    - name: Copy the Apache configuration file to remote host
      copy: src=files/httpd.conf.template dest=/etc/httpd/conf/httpd.conf owner=root group=root mode=644
    - name: Create the VHOST.D Directory on the remote host
      file: path=/etc/httpd/vhost.d state=directory mode=755
    - name: Copy and untar the source for the site
      unarchive: src=files/sitecode.tar.gz dest={{ apache_dir }}
    - name: Copy the default vhost configuration file
      copy: src=files/default.conf.template dest=/etc/httpd/vhost.d/default.conf owner=root group=root mode=644
      notify:
        - StartHttpd
        - TestHttpd
        - DisplayResult
  handlers:
    - name: StartHttpd
      service: name={{ apache_pkg }} state=started
    - name: TestHttpd
      shell: curl http://{{ apache_fqdn }}
      register: result
    - name: DisplayResult
      debug: var=result
