--- # UNTIL EXAMPLE
- hosts: apacheweb
  sudo: yes
  connection: ssh
  user: test
  gather_facts: no
  tasks:
    - name: Installing Apache Web Server
      yum: pkg=httpd state=latest
    - name: Verify Service Status
      shell: systemctl status httpd
      register: result
      until: result.stdout.find("active (running)") != -1
      retries: 5
      delay: 5
    - debug: var=result
