--- # WHEN Playbook Example
- hosts: aptserver
  user: test
  sudo: yes
  connection: ssh
  vars:
    playbook_type: conditionalexample
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  tasks:
    - name: Install Apache Appropriate to the Distribution Type (Debian/Ubuntu)
      command: apt-get -y install apache2
      when: ansible_os_family == "Debian"
    - name: Install Apache Appropriate to the Distribution Type (RedHat/CentOS)
      command: yum -y install httpd
      when: ansible_os_family == "RedHat"
